name: breastCancerAwareness
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
        
  firebase_ml_vision: ^0.9.7
  image_picker: ^0.6.7+11
  cupertino_icons: ^0.1.2
  translator: ^0.1.5
  pdf: ^1.11.2
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.18
  provider: ^4.3.2+2
  shared_preferences: ^0.5.6+2
  easy_localization: ^2.3.3
  connectivity: ^0.4.9+3
  flutter_launcher_icons: ^0.8.1

 
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/splash_bg.png
    - assets/icons/logo.png
    - assets/icons/avatar_splash.png
    - assets/icons/splash_text.png
    - assets/icons/down_arrow.png
    - assets/icons/home.png
    - assets/icons/avatar_home.png
    - assets/icons/app_icon.png
    - assets/locales/en-US.json
    - assets/locales/hi-IN.json
    - assets/locales/fr-US.json
    - assets/locales/es-ES.json
    - assets/data/glossary_en.json
    - assets/data/glossary_hi.json
    - assets/data/glossary_fr.json
    - assets/data/glossary_es.json

