import 'package:easy_localization/easy_localization.dart';

const String kAppName = "bea";
String kTranslator = "translator".tr();
String kOriginalDocument = "original-doc".tr();
const String kTranslatedDocument = "Translated Document";
String kUploadDocument = "translate-doc".tr();
String kTakePicture = "take-picture".tr();
const String kdocumentTranslator = "Document Translator";
String kGlossary = "to-glossary".tr();
String kMyQuestions = "my-questions".tr();
const String kViewDocuments = "View Uploaded Documents";
String kKnowMore = "know-more".tr();
String title = 'title'.tr();
String myFiles = "my-files".tr();
String glossary = "glossary".tr();
String hintSearch = "search".tr();
String label2 = "home".tr();
String label3 = "my-files".tr();
String label4 = "saved-questions".tr();
String label5 = "settings".tr();
String homeScreenSubtitle = "today".tr();
String noInternetMessage = "Please connect to the internet!";
